### PR TITLE
Relative file path for all(?) versions of Brakeman

### PR DESCRIPTION
**Pull request by presidentbeef**
I broke guard-brakeman in Brakeman 4.5.1 when I switched Brakeman from using strings to represent paths internally to `Brakeman::FilePath`.

`Brakeman::Warning#relative_path` has been in Brakeman for a long time, so that *should* be the preferred API. However...I also removed that in 4.5.1. I should not have done that. I will add it back in 4.5.2 (or whatever the next release is).

Even after that, though, it would still leave guard-brakeman incompatible with Brakeman 4.5.1. So this patch will work with 4.5.1 and any other supported version.

I tested with Brakeman 4.5.1, 4.5.0, and 2.1.1.

### CODE REVIEW

**Comment by presidentbeef** [comment]
Oops, forgot to credit https://stackoverflow.com/questions/56623617/why-is-brakeman-guard-raising-nomethoderror-undefined-method-gsub for raising the issue.

**Comment by ahharvey** [comment]
thanks @presidentbeef for this update. 

can I confirm that the issue described on Stackoverflow (NoMethodError: undefined method `gsub' for #<Brakeman::FilePath>) should now be resolved with the latest version of Brakeman?

I am still getting this same error with guard-brakeman 0.8.3 and brakeman 4.6.1.

**Comment by presidentbeef** [comment]
@ahharvey - It will not work without an update to guard-brakeman.

I realize the way I phrased my comment above was misleading. I had hoped to just update Brakeman to fix the issue, but treating `Brakeman::Warning#file` as a plain string just won't work any more.

@oreoshake *poke, poke*

**Comment by oreoshake** [comment]
You caught me at a great time, I'm working on this in https://github.com/guard/guard-brakeman/pull/37. I've merge this branch into that branch so I'll close this one out and work that one to completion.

**Comment by oreoshake** [comment]
0.8.4 released https://rubygems.org/gems/guard-brakeman/versions/0.8.4
